<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'objectpool\\objectpool' => '/ObjectPool.php',
                'objectpool\\pool' => '/Pool.php',
                'objectpool\\tests\\traits\\internaluses' => '/../../tests/traits/internalUses.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
